name: ceiba
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  get: ^4.6.1
  yaml: ^3.1.0
  hive: ^2.1.0
  http: ^0.13.4
  dartz: ^0.10.1
  flutter_svg: ^1.0.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Imgs/
    - lib/app/i18n/langs/

  fonts:

    - family: NunitoRegular
      fonts:
        - asset: assets/Font/Nunito/Nunito-Regular.ttf

    - family: NunitoSemiBold
      fonts:
        - asset: assets/Font/Nunito/Nunito-SemiBold.ttf

    - family: NunitoBold
      fonts:
        - asset: assets/Font/Nunito/Nunito-Bold.ttf

    - family: NunitoExtraBold
      fonts:
        - asset: assets/Font/Nunito/Nunito-ExtraBold.ttf

    - family: NunitoBlack
      fonts:
        - asset: assets/Font/Nunito/Nunito-Black.ttf

    - family: OpenSasRegular
      fonts:
        - asset: assets/Font/Open_Sans/OpenSans-Regular.ttf

    - family: OpenSasSemiBold
      fonts:
        - asset: assets/Font/Open_Sans/OpenSans-SemiBold.ttf

    - family: OpenSasBold
      fonts:
        - asset: assets/Font/Open_Sans/OpenSans-Bold.ttf   